# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: placeless
email: placeless@outlook.com
description: "question came and went, like a helicopter over head..."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://placeless.net" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
timezone: Asia/Shanghai
encoding: UTF-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

# paginate: 10
# paginate_path: "/page:num/"
#
#
# gems: [jekyll-paginate]
